url: http://chrisbr.github.io/skiclub/
baseurl: /skiclub/
webmaster: christian@bruckmayer.net
webmaster_rot13: puevfgvna@oehpxznlre.arg

# Site settings
title: Skiclub Kühlenfels
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# board
# Note that the emails are encoded in ROT13 for obfuscating
# http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/
people:
  - name: Uwe Wiegärtner
    pic: uwe
    position: 1. Vorstand
    email: Uwe.Wiegaertner@Allianz.de
    email_rot13: Hjr.Jvrtnregare@Nyyvnam.qr
    address: Meine Adresse
    zip: 91278
    city: Pottenstein
    phone: +49 9243 123456

  - name: Frank Eckert
    pic: frank
    position: 2. Vorstand
    email: f-eckert@web.de
    email_rot13: s-rpxreg@jro.qr

  - name: Oliver Sander
    pic: olli
    position: Sportdirektor
    email: sanderoliver@t-online.de
    email_rot13: fnaqrebyvire@g-bayvar.qr

  - name: Stefan Langhojer
    pic: 1
    position: Schriftführer
    email: s.langhojer@web.de
    email_rot13: f.ynatubwre@jro.qr

  - name: Georg Herzing
    pic: 1
    position: Kassenwart
    email: georg.herzing@web.de
    email_rot13: trbet.uremvat@jro.qr

# Social networks
social:
  - title: facebook
    url: https://www.facebook.com

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jemoji