webmaster: christian@bruckmayer.net
webmaster_rot13: puevfgvna@oehpxznlre.arg
timezone: Europe/Berlin

exclude: [ Gemfile, Gemfile.lock, LICENSE, README.md, vendor ]

# Site settings
title: Skiclub Kühlenfels
email: christian@bruckmayer.net
description: "Internetauftritt des Skiclub Kühlenfels."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

future: true

# board
# Note that the emails are encoded in ROT13 for obfuscating
# http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/
people:
  - name: Uwe Wiegärtner
    pic: uwe
    position: 1. Vorstand
    email: uwe@skiclub-kuehlenfels.de
    address: Zur Allee 52
    zip: 91278
    city: Pottenstein  / OT Kühlenfels
    phone: 09243 903045

  - name: Frank Eckert
    pic: frank
    position: 2. Vorstand
    email: frank@skiclub-kuehlenfels.de

  - name: Oliver Sander
    pic: olli
    position: Sportdirektor
    email: oliver@skiclub-kuehlenfels.de

  - name: Stefan Langhojer
    pic: stefan
    position: Schriftführer
    email: stefan@skiclub-kuehlenfels.de

  - name: Georg Herzing
    pic: georg
    position: Kassenwart
    email: georg@skiclub-kuehlenfels.de

# Social networks
social:
  - title: facebook
    url: https://www.facebook.com

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jemoji
